language: go

go:
  - 1.2
  - release
  
script: "cd tests && go test"

before_install:
  - export GOPATH=/home/travis/gopath
  - export PATH=$GOPATH/bin:$PATH
  - go get launchpad.net/gocheck

install: make
